# Generated by Django 5.0.6 on 2024-05-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostawcy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_dostawcy', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Oceny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField(default=5)),
                ('recenzja', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('opis', models.TextField(default='')),
                ('liczba_sztuk', models.PositiveSmallIntegerField(default=10)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('zdjecie_produktu', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
                ('dostawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablety.dostawcy')),
            ],
        ),
    ]
