# Generated by Django 5.0.6 on 2024-05-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceny',
            name='produkt',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='tablety.produkty'),
            preserve_default=False,
        ),
    ]
